datastore_path: internal-data
its_config:
  jira:
    url:
      label: JIRA URL
      default_value: ""
      required: true
    username:
      label: JIRA User
      default_value: ""
      required: true
    password:
      label: JIRA Token
      default_value: ""
      password: true
      required: true
    projects:
      default_value: ""
      required: true
    api_options:
      hidden: true
      options:
        limit: 100
        fields:
          - summary
          - description
          - status
          - project
          - issuetype
llm_config:
  openai:
    api_key:
      label: OpenAI API Key
      default_value: ""
      password: true
      required: true
    embedding_model:
      label: "Embedding Model"
      default_value: text-embedding-ada-002
    llm_model:
      label: "LLM Model"
      default_value: gpt-3.5-turbo