datastore_path: internal-data
its_config:
  jira:
    url:
      label: JIRA URL
      value: ${oc.env:JIRA_URL,""}
      required: true
      is_text_input: true
    username:
      label: JIRA User
      value: ${oc.env:JIRA_USER,""}
      required: true
      is_text_input: true
    password:
      label: JIRA Token
      value: ${oc.env:JIRA_TOKEN,""}
      password: true
      required: true
      is_text_input: true
    projects:
      label: Projects
      value: ${oc.env:JIRA_PROJECTS,""}
      required: true
      is_text_input: true
    api_options:
      hidden: true
      options:
        limit: 100
        fields:
          - summary
          - description
          - status
          - project
          - issuetype
    issue_create_options:
      hidden: true
      options:
        fields:
          - field_id: issuetype
            label: Issue Type
            value:
                - Task
                - Bug
          - field_id: duedate
            label: Due Date (YYYY-MM-DD)
            value: ""
        custom_fields: ${oc.decode:${oc.env:JIRA_CUSTOM_FIELDS, null}}
llm_config:
  openai:
    api_key:
      label: OpenAI API Key
      value: ${oc.env:OPENAI_API_KEY,""}
      password: true
      required: true
      is_text_input: true
    embedding_model:
      label: "Embedding Model"
      value:
        - text-embedding-ada-002
      is_text_input: true
    llm_model:
      label: "LLM Model"
      value:
        - gpt-3.5-turbo